apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        image: docker.pkg.github.com/weiweizhangr/helloworld/my-node-app:latest  # 更新镜像版本
        ports:
        - containerPort: 3000