apiVersion: v1
kind: Secret
metadata:
  name: github-registry-credentials
  namespace: argocd  # 替换为你的命名空间
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJ3ZWl3ZWl6aGFuZ3IiLAogICAgICAicGFzc3dvcmQiOiAiZ2hwX21HWnhBZE9TVjdqSEh6MDZtVEplc3dERlBKU0hPNjFtOVRjdiIsCiAgICAgICJlbWFpbCI6ICJ3ZWl3ZWkuYi56aGFuZ0ByYWt1dGVuLmNvbSIsCiAgICAgICJhdXRoIjogImQyVnBkMlZwZW1oaGJtZHlPbWRvY0Y5dFIxcDRRV1JQVTFZM2FraEllakEyYlZSS1pYTjNSRVpRU2xOSVR6WXhiVGxVWTNZPSIKICAgIH0KICB9Cn0K
type: kubernetes.io/dockerconfigjson